### ISSUE TITLE
Website gives type error when I add a certain image

### ISSUE THREAD

**Issue by angelinasav20** [klalicki/portfolio-builder#1]
Whenever I add a png of one of my portfolio pieces into the projects section it gives a type error. I asked shauna about it and she thought it was the file name so I changed it, but I tried it a couple minutes ago and it still happened. It happens with some of my other portfolio images too. Could the generator just not take certain pngs? hers some screenshots of what im getting. 
![Screenshot 2024-04-28 202425](https://github.com/klalicki/portfolio-builder/assets/157765669/2c5d6b4e-c79f-44ef-ba27-4131b198111d)
![Screenshot 2024-04-28 203340](https://github.com/klalicki/portfolio-builder/assets/157765669/1eb830a8-2964-47e8-aecd-683de61d8b0a)

**Comment by klalicki** [comment]
Hi! I'll take a look at your repo and see if I can figure this out and fix it.

**Comment by klalicki** [comment]
@angelinasav20 can you make sure that all your code is committed and pushed? It looks like it's not synced back to GitHub right now. In the Source Control panel, the 'Commit' button will change to a 'Sync' button - once you click that I'll be able to take a look and see what went wrong.

**Comment by angelinasav20** [comment]
you should be able to take a look, everything is pushed!

**Comment by klalicki** [comment]
@angelinasav20  I figured out what the bug was! your image had an uppercase PNG as its extension, and my code was only looking for images with lowercase extensions. I fixed the issue in a pull request on your repo. 
If you click into the pull request and click the 'Merge' button it will pull those edits into your copy of the site. You will then have to re-sync your codespace when you open it again. The 'Commit' button should turn into a 'Sync' or 'Pull' button; I can't remember which it is.

Let me know if that works! If you're having trouble with the pull request, Shauna or I can help you with that in class tomorrow night.
